/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace SubAccounts {
  export type SubAccountStruct = {
    owner: string;
    encryptedAccount: string;
    network: string;
    accountAddress: string;
  };

  export type SubAccountStructOutput = [string, string, string, string] & {
    owner: string;
    encryptedAccount: string;
    network: string;
    accountAddress: string;
  };
}

export interface SubAccountsInterface extends utils.Interface {
  functions: {
    "getAllSubAccounts()": FunctionFragment;
    "getSubAccountsByAddress(address)": FunctionFragment;
    "storeSubAccount(string,string,string)": FunctionFragment;
    "subAccounts(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getAllSubAccounts"
      | "getSubAccountsByAddress"
      | "storeSubAccount"
      | "subAccounts"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllSubAccounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubAccountsByAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "storeSubAccount",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "subAccounts",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllSubAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubAccountsByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeSubAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subAccounts",
    data: BytesLike
  ): Result;

  events: {
    "SubAccountStored(address,string,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SubAccountStored"): EventFragment;
}

export interface SubAccountStoredEventObject {
  owner: string;
  encryptedAccount: string;
  network: string;
  accountAddress: string;
}
export type SubAccountStoredEvent = TypedEvent<
  [string, string, string, string],
  SubAccountStoredEventObject
>;

export type SubAccountStoredEventFilter =
  TypedEventFilter<SubAccountStoredEvent>;

export interface SubAccounts extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SubAccountsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAllSubAccounts(
      overrides?: CallOverrides
    ): Promise<[SubAccounts.SubAccountStructOutput[]]>;

    getSubAccountsByAddress(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<[SubAccounts.SubAccountStructOutput[]]>;

    storeSubAccount(
      _encryptedAccount: string,
      _network: string,
      _accountAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    subAccounts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string] & {
        owner: string;
        encryptedAccount: string;
        network: string;
        accountAddress: string;
      }
    >;
  };

  getAllSubAccounts(
    overrides?: CallOverrides
  ): Promise<SubAccounts.SubAccountStructOutput[]>;

  getSubAccountsByAddress(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<SubAccounts.SubAccountStructOutput[]>;

  storeSubAccount(
    _encryptedAccount: string,
    _network: string,
    _accountAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  subAccounts(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string] & {
      owner: string;
      encryptedAccount: string;
      network: string;
      accountAddress: string;
    }
  >;

  callStatic: {
    getAllSubAccounts(
      overrides?: CallOverrides
    ): Promise<SubAccounts.SubAccountStructOutput[]>;

    getSubAccountsByAddress(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<SubAccounts.SubAccountStructOutput[]>;

    storeSubAccount(
      _encryptedAccount: string,
      _network: string,
      _accountAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    subAccounts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string] & {
        owner: string;
        encryptedAccount: string;
        network: string;
        accountAddress: string;
      }
    >;
  };

  filters: {
    "SubAccountStored(address,string,string,string)"(
      owner?: string | null,
      encryptedAccount?: null,
      network?: null,
      accountAddress?: null
    ): SubAccountStoredEventFilter;
    SubAccountStored(
      owner?: string | null,
      encryptedAccount?: null,
      network?: null,
      accountAddress?: null
    ): SubAccountStoredEventFilter;
  };

  estimateGas: {
    getAllSubAccounts(overrides?: CallOverrides): Promise<BigNumber>;

    getSubAccountsByAddress(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    storeSubAccount(
      _encryptedAccount: string,
      _network: string,
      _accountAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    subAccounts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAllSubAccounts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSubAccountsByAddress(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    storeSubAccount(
      _encryptedAccount: string,
      _network: string,
      _accountAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    subAccounts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
